server:
  port: 8082

spring:
  application:
    name: transaction-service

  datasource:
    url: ${DB_URL}
    username: transaction-user
    password: transaction-pass

  jpa:
    hibernate:
      ddl-auto: update